### PR TITLE
initial pass at plot_rink

### LINKED ISSUE #4: plot_rink() helper
Following up this Twitter thread:

https://twitter.com/michael_chirico/status/1301906742679396355

I have most of the code for `plot_rink()` done using `base` plotting & assisted by the NHL rulebook:

https://nhl.bamcontent.com/images/assets/binary/308893668/binary-file/file.pdf

Advantage over raster being auto-scaling.

Shouldn't be too hard to come up with a `ggplot_rink` or `ggrink` but I'm terrible with `ggplot2` so I would leave that to someone else.

Filing an initial implementation shortly...

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #4 

Leaving it here for now. There are a few more bells and whistles that could be added:

 - Trapezoid behind the net
 - All other rink markings (hash markings _inside_ D zone circles, and "ref's crease" at center ice)
 - Real widths of lines -- would need to make the neutral/center ice/goal lines into rectangles, everything else into annuli
 - Could also make `plot_half_rink()` for plotters who may be reflecting data to only be on one side of the rink

But I wanted to stop here before I got too ambitious and pause for some feedback.

What else do you want out of the PR? I didn't add any tests (I never know what sorts of tests to add for plotting functionality)... I could add some "ad hoc" tests to this PR to show basic functionality?

Also note: I ~half-ran `devtools::document()`. I apparently have a newer version of `roxygen2` than was used on the last build here, and the new version made a huge diff on other .Rd files. So I leave that to you to update first if you choose...

### CODE REVIEW

**Comment by MichaelChirico** [comment]
BTW here is the current output from `plot_rink()`
Screenshot from 2020-09-04 15-15-28

**Comment by MichaelChirico** [comment]
Now with painted crease

Selection_001

**Comment by MichaelChirico** [comment]
Now with hash marks

Selection_002

**Comment by MichaelChirico** [comment]
With trapezoid

Selection_003

**Comment by hswerdfe** [comment]
Looks great: @MichaelChirico if I had a suggestion it would be to add in the actual net, and to put an alpha on blue shading for the crease and the net.

**Comment by jozefhajnala** [comment]
My apologies for taking like half a year, this is fantastic work! I just added a test and some vanity code style changes. Thank you very much for such a valuable contribution!

**Comment by MichaelChirico** [comment]
HTH Jozef!

@hswerdfe thanks! could you file as a follow-up issue?

**Pull request merged**
